CREATE TABLE DC_KEYS (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  REFINED_KEY VARCHAR(32) BINARY NOT NULL,
  DC_SITE_ID INTEGER UNSIGNED NOT NULL,
  DC_FORUM_ID INTEGER UNSIGNED NOT NULL,
  ITEM_URL VARCHAR(1024) BINARY NOT NULL,
  DB_URL VARCHAR(255) BINARY NOT NULL,
  DB_NAME VARCHAR(255) BINARY NOT NULL,
  TABLE_NAME VARCHAR(255) BINARY NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE DW_KEYS (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  REFINED_KEY VARCHAR(32) BINARY NOT NULL,
  TE_ITEM_KEY INTEGER UNSIGNED NOT NULL,
  DC_SITE_ID INTEGER UNSIGNED NOT NULL,
  DC_FORUM_ID INTEGER UNSIGNED NOT NULL,
  ITEM_URL VARCHAR(1024) BINARY NOT NULL,
  DB_URL VARCHAR(255) BINARY NOT NULL,
  DB_NAME VARCHAR(255) BINARY NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE TM_KEYS (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  REFINED_KEY VARCHAR(32) BINARY NOT NULL,
  TM_ITEM_ID INTEGER UNSIGNED NOT NULL,
  TM_SITE_ID INTEGER UNSIGNED NOT NULL,
  TM_FORUM_ID INTEGER UNSIGNED NOT NULL,
  ITEM_URL VARCHAR(1024) BINARY NOT NULL,
  PRIMARY KEY(ID)
);


